name: Publish
permissions: {}

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Online Document
      permissions:
        contents: read
      run: |
        git config --local --get remote.origin.url
        cd docs/build_docs
        bash build.sh latest
        
    - name: Push to github
      permissions:
        contents: write
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_tmp/gh-pages
        publish_branch: gh-pages
       
